export const jobData = [
  {
      id: 1,
      company: "LinkedIn",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "UI/UX Designer",
      location: "New York, US",
      type: "Fulltime",
      timeAgo: "4 mins ago",
      description: "Design user-friendly interfaces and experiences.",
      salary: "40K - 50K",
      industry: "Software",
      tools: ["Adobe XD", "Figma"],
      featured: true
  },
  {
      id: 2,
      company: "Adobe",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Full Stack Engineer",
      location: "San Jose, US",
      type: "Part-time",
      timeAgo: "15 mins ago",
      description: "Develop and maintain scalable web applications.",
      salary: "50K - 60K",
      industry: "Software",
      tools: ["React", "Node.js"],
      featured: true
  },
  {
      id: 3,
      company: "Goldman Sachs",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Investment Analyst",
      location: "New York, US",
      type: "Fulltime",
      timeAgo: "1 hour ago",
      description: "Analyze financial data and market trends.",
      salary: "55K - 60K",
      industry: "Finance",
      tools: ["Excel", "Tableau"],
      featured: false
  },
  {
      id: 4,
      company: "Tesla",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Mechanical Engineer",
      location: "Austin, US",
      type: "Fulltime",
      timeAgo: "3 hours ago",
      description: "Design mechanical components for electric vehicles.",
      salary: "45K - 55K",
      industry: "Automotive",
      tools: ["SolidWorks", "AutoCAD"],
      featured: true
  },
  {
      id: 5,
      company: "Amazon",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Cloud Solutions Architect",
      location: "Seattle, US",
      type: "Contract",
      timeAgo: "5 hours ago",
      description: "Design cloud-based systems for enterprise clients.",
      salary: "50K - 60K",
      industry: "Technology",
      tools: ["AWS", "Terraform"],
      featured: true
  },
  {
      id: 6,
      company: "JP Morgan Chase",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Financial Advisor",
      location: "Chicago, US",
      type: "Fulltime",
      timeAgo: "6 hours ago",
      description: "Provide financial planning services to clients.",
      salary: "30K - 50K",
      industry: "Finance",
      tools: ["CRM", "PowerPoint"],
      featured: false
  },
  {
      id: 7,
      company: "Google",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Machine Learning Engineer",
      location: "Mountain View, US",
      type: "Fulltime",
      timeAgo: "8 hours ago",
      description: "Develop AI models and systems for large-scale applications.",
      salary: "50K - 60K",
      industry: "Software",
      tools: ["TensorFlow", "PyTorch"],
      featured: true
  },
  {
      id: 8,
      company: "Facebook",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Social Media Manager",
      location: "California, US",
      type: "Part-time",
      timeAgo: "9 hours ago",
      description: "Manage social media accounts and campaigns.",
      salary: "20K - 30K",
      industry: "Marketing",
      tools: ["Hootsuite", "Canva"],
      featured: false
  },
  {
      id: 9,
      company: "Microsoft",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Azure Specialist",
      location: "Redmond, US",
      type: "Contract",
      timeAgo: "10 hours ago",
      description: "Deploy and maintain Azure cloud solutions.",
      salary: "40K - 50K",
      industry: "Software",
      tools: ["Azure", "PowerShell"],
      featured: true
  },
  {
      id: 10,
      company: "Stripe",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Payment Integration Engineer",
      location: "Dublin, Ireland",
      type: "Fulltime",
      timeAgo: "12 hours ago",
      description: "Implement payment processing systems for businesses.",
      salary: "50K - 60K",
      industry: "Finance",
      tools: ["Ruby", "JavaScript"],
      featured: false
  },
  {
      id: 11,
      company: "Netflix",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Frontend Developer",
      location: "Los Angeles, US",
      type: "Fulltime",
      timeAgo: "14 hours ago",
      description: "Develop and maintain UI for streaming services.",
      salary: "35K - 50K",
      industry: "Entertainment",
      tools: ["React", "CSS"],
      featured: true
  },
  {
      id: 12,
      company: "Intel",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Chip Design Engineer",
      location: "Santa Clara, US",
      type: "Fulltime",
      timeAgo: "15 hours ago",
      description: "Design next-generation processors and hardware.",
      salary: "50K - 60K",
      industry: "Hardware",
      tools: ["Verilog", "SystemVerilog"],
      featured: false
  },
  {
      id: 13,
      company: "Oracle",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Database Administrator",
      location: "Remote",
      type: "Fulltime",
      timeAgo: "16 hours ago",
      description: "Manage and optimize large-scale database systems.",
      salary: "40K - 50K",
      industry: "Software",
      tools: ["SQL", "Oracle DB"],
      featured: true
  },
  {
      id: 14,
      company: "Spotify",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Backend Developer",
      location: "Stockholm, Sweden",
      type: "Part-time",
      timeAgo: "18 hours ago",
      description: "Develop scalable backend systems for music streaming.",
      salary: "30K - 45K",
      industry: "Entertainment",
      tools: ["Node.js", "Java"],
      featured: false
  },
  {
      id: 15,
      company: "Slack",
      logo: "https://jobbox-nextjs-v3.vercel.app/_next/static/media/right-job-head.20bf0a8a.svg",
      title: "Customer Support Specialist",
      location: "Remote",
      type: "Part-time",
      timeAgo: "20 hours ago",
      description: "Provide technical support to customers.",
      salary: "20K - 30K",
      industry: "Software",
      tools: ["Zendesk", "Slack"],
      featured: false
  }
];



export const industryFilters = [
  { name: "All", count: 180 },
  { name: "Software", count: 12 },
  { name: "Finance", count: 23 },
  { name: "Recruiting", count: 43 },
  { name: "Management", count: 65 },
  { name: "Advertising", count: 76 }
];

export const salaryRanges = [
  { name: "All", count: 145 },
  { name: "$0k - $20k", count: 56 },
  { name: "$20k - $40k", count: 37 },
  { name: "$40k - $60k", count: 75 }
];